# Generated by Django 2.0.9 on 2018-10-25 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('billing', 'Billing'), ('shipping', 'Shipping')], max_length=180)),
                ('address_line_1', models.CharField(max_length=180)),
                ('address_line_2', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=180)),
                ('country', models.CharField(default='India', max_length=180)),
                ('state', models.CharField(max_length=180)),
                ('postal_code', models.CharField(max_length=180)),
                ('billing_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.BillingProfile')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
