# Generated by Django 2.0.9 on 2018-10-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=65),
        ),
    ]
